### PR TITLE
Change the moped dependency to be the same as mongoid

### PR DESCRIPTION
**Pull request by Velkitor**

### CODE REVIEW

**Comment by pootsbook** [comment]
Yes please.

**Comment by gautamrege** [comment]
:+1:

**Comment by bnorton** [comment]
:thumbsup:

**Comment by djd** [comment]
:thumbsup:

**Comment by jonstorer** [comment]
:+1:

**Comment by cpuguy83** [comment]
Shouldn't the dependency just be mongoid?  Mongoid should take care of the moped dependancy.

**Comment by Velkitor** [comment]
cpuguy83 the moped dependency was already present in the gem spec.  I just updated that so that functionality would not be changed.

**Comment by cpuguy83** [comment]
@Velkitor Yes, but if we just remove the moped dependency this won't be a problem in the future.

**Comment by Velkitor** [comment]
True, but I am not the gem author so I did not want to make that decision for them.  It could be changed to depend on mongoid, and not moped.

**Comment by jonstorer** [comment]
I agree with @cpuguy83, making the dependency mongoid should give kiqstand all it needs. How do we get this prioritized?

**Comment by arthurnn** [comment]
i will take a look on this still tonight...

On Friday, October 18, 2013, Jonathon Storer wrote:

> I agree with @cpuguy83 https://github.com/cpuguy83, making the
> dependency mongoid should give kiqstand all it needs. How do we get this
> prioritized?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mongoid/kiqstand/pull/7#issuecomment-26642694
> .

## 

Arthur Nogueira Neves
Follow me @arthurnn http://www.twitter.com/arthurnn89

**Comment by xpepermint** [comment]
Is this gem needed in rails4+?

**Comment by arthurnn** [comment]
@xpepermint nop.. on rails4 , mongoid 4, kiqstand wont be necessary anymore.

**Comment by arthurnn** [comment]
Thanks for the PR, but we actually should remove the moped dependency, as mongoid should bring it. via https://github.com/mongoid/kiqstand/commit/0ae20664f87d6932e32129fb541e5ef59ce6db13

**Pull request closed without merging**
